name: CI
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-env:
    name: testing-environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE_QUOT }}" > .env
          cat .env

      - name: "Install the project"
        run: npm install

      - name: "Run the tests"
        run: npm test
